import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ posts }) {
	posts && console.log(posts.slice(0, 5));

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<h1>Next.js 13</h1>
				<br />
				{posts.slice(0, 5).map((post, idx) => (
					<h3 key={idx}>{post.title}</h3>
				))}
			</main>
		</>
	);
}

export const getStaticProps = async () => {
	const res = await fetch('https://jsonplaceholder.typicode.com/posts/');
	const posts = await res.json();

	console.log(posts.slice(0, 5));

	return {
		props: { posts }
	};
};
